/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AchievementItem: typeof import('./src/components/AchievementItem.vue')['default']
    Achievements: typeof import('./src/components/Achievements.vue')['default']
    AchievementsProvider: typeof import('./src/components/AchievementsProvider.vue')['default']
    Advantages: typeof import('./src/components/Advantages.vue')['default']
    AdvantagesItem: typeof import('./src/components/AdvantagesItem.vue')['default']
    AdvantagesProvider: typeof import('./src/components/AdvantagesProvider.vue')['default']
    CompanyName: typeof import('./src/components/CompanyName.vue')['default']
    EditableSpan: typeof import('./src/components/EditableSpan.vue')['default']
    EduAchievementItem: typeof import('./src/components/EduAchievementItem.vue')['default']
    EduAchievementProvider: typeof import('./src/components/EduAchievementProvider.vue')['default']
    EduAchievements: typeof import('./src/components/EduAchievements.vue')['default']
    EducationDuration: typeof import('./src/components/EducationDuration.vue')['default']
    Educations: typeof import('./src/components/Educations.vue')['default']
    EducationsProvider: typeof import('./src/components/EducationsProvider.vue')['default']
    Galleries: typeof import('./src/components/Galleries.vue')['default']
    GalleryItem: typeof import('./src/components/GalleryItem.vue')['default']
    GalleryProvider: typeof import('./src/components/GalleryProvider.vue')['default']
    InstitutionName: typeof import('./src/components/InstitutionName.vue')['default']
    JobTitle: typeof import('./src/components/JobTitle.vue')['default']
    Major: typeof import('./src/components/Major.vue')['default']
    Operable: typeof import('./src/components/Operable.vue')['default']
    Responsibilities: typeof import('./src/components/Responsibilities.vue')['default']
    ResponsibilityItem: typeof import('./src/components/ResponsibilityItem.vue')['default']
    ResponsibilityProvider: typeof import('./src/components/ResponsibilityProvider.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WEProvider: typeof import('./src/components/WEProvider.vue')['default']
    WorkingDuration: typeof import('./src/components/WorkingDuration.vue')['default']
    WorkingExperiences: typeof import('./src/components/WorkingExperiences.vue')['default']
  }
}
